### ISSUE TITLE
Review MCD et MLD

### ISSUE THREAD

**Issue by AntoineRoulinCPNV** [NicolasGlassey/PROJWEB-INFOWEB#2]
Donner un retour sur les dernières modifications effectuées sur le MCD et MLD après la Sprint Review du 12.05.2021.

Modifications apportées dans le MCD :
Changement du terme "Utilisateurs" par "Vendeurs".
Changement du terme "Numéro de châssis" par "Numéro de série".
Changement du terme "Roue motrice" par "Traction".
Changement des flèches par des ligne simple dans les relations.
Déplacement des identifiants naturels vers le haut des entités.

Modifications apportées dans le MLD :
Changement du terme "users" par "sellers".
Changement du terme "drivingwheel" par "traction".
Modifications des nombres de caractères maximum dans plusieurs champs.

Lien direct pour le MCD : https://github.com/NicolasGlassey/PROJWEB-INFOWEB/blob/feature/MCD-MLD/doc/MCD/MCD_ProjWEB_CLASSICCAR_ARN-NED.pdf

Lien direct pour le MLD : https://github.com/NicolasGlassey/PROJWEB-INFOWEB/blob/feature/MCD-MLD/doc/MLD/MLD_ProjWEB_ARN-NED.pdf

**Comment by NicolasGlassey** [comment]
@AntoineRoulinCPNV 

Selon notre meeting:

1) MCD -> basez-vous sur le métier des garagistes (exemple : autoscout)
2) revoir format d'impression mcd / mld

**Comment by AntoineRoulinCPNV** [comment]
@NicolasGlassey 

test

**Comment by AntoineRoulinCPNV** [comment]
@NicolasGlassey 

J'ai apporté les modification discuté durant la review du MCD et MLD.

Lien direct vers le MCD : https://github.com/NicolasGlassey/PROJWEB-INFOWEB/blob/feature/MCD-MLD/doc/MCD/MCD_ProjWEB_CLASSICCAR_ARN-NED.png

Lien direct vers le MLD : https://github.com/NicolasGlassey/PROJWEB-INFOWEB/blob/feature/MCD-MLD/doc/MLD/MLD_ProjWEB_ARN-NED.png

**Comment by NicolasGlassey** [comment]
@AntoineRoulinCPNV 

Pour moi c'est tout bon. Je termine l'issue.
