### ISSUE TITLE
Warning alerts problem

### ISSUE THREAD

**Issue by NolanEvard** [NicolasGlassey/PROJWEB-INFOWEB#3]
J'ai terminé de modifier le système d'erreurs cependant il y a un petit bémol. Dans le fichier jsonManager.php je récupère le résultat du fopen chargé d'ouvrir le fichier JSON. Cependant lorsque ce fopen échoue à ouvrir le fichier JSON un WARNING s'affiche quand même sur la page de boutique. 

![image](https://user-images.githubusercontent.com/61775725/119685257-7c28c680-be45-11eb-8a35-c382fc604205.png)

J'ai donc dû ajouter quelques lignes de code pour contrer cela mais je ne suis pas sûr que ce soit optimal. Pourriez vous jeter un coup d'œil aux lignes 29-31 du fichier JsonManager.php.

**Comment by NicolasGlassey** [comment]
Bonsoir Nolan,

Je vous propose de tester si le fichier existe avant d'essayer de l'ouvrir. Evitant ainsi de réaliser un fopen sur un fichier inexistant.

Le résultat sur l'IHM est celui-là :

![image](https://user-images.githubusercontent.com/5616312/119735668-f9bbf900-be7c-11eb-9f81-78d08d6a283a.png)

Et voilà le commit:
https://github.com/NicolasGlassey/PROJWEB-INFOWEB/commit/5e7b34a236978d79d60b13bf82eaaa6d530aa464

On regarde demain ensemble si besoin.

Bonne soirée !

**Comment by NolanEvard** [comment]
Bonjour,

Je suis conscient que le fichier n'existe pas, c'était dans le but de gérer cette exception que j'ai fait ce test. Mais il est vrai que c'est une exception qui est assez peu probable et donc qui ne mérite certainement pas que l'on y passe trop de temps.

Merci pour le temps passé pour cette issue et meilleures salutations.

Nolan Evard , étudiant
CPNV filière informatique, Sainte-Croix
SI-MI2b
***@***.***

On May 26, 2021 23:51, NicolasGlassey ***@***.***> wrote:

Bonsoir Nolan,

Je vous propose de tester si le fichier existe avant d'essayer de l'ouvrir. Evitant ainsi de réaliser un fopen sur un fichier inexistant.

Le résultat sur l'IHM est celui-là :

[image]<https://user-images.githubusercontent.com/5616312/119735668-f9bbf900-be7c-11eb-9f81-78d08d6a283a.png>

Et voilà le commit:
5e7b34a<https://github.com/NicolasGlassey/PROJWEB-INFOWEB/commit/5e7b34a236978d79d60b13bf82eaaa6d530aa464>

On regarde demain ensemble si besoin.

Bonne soirée !

**Comment by NolanEvard** [comment]
Veuillez m'excuser j'ai mal lu votre mail précédent. Je vais faire les corrections nécessaires pour éviter le problème.

Meilleures salutations.

Nolan Evard , étudiant
CPNV filière informatique, Sainte-Croix
SI-MI2b
***@***.***

On May 27, 2021 08:04, EVARD Nolan ***@***.***> wrote:
Bonjour,

Je suis conscient que le fichier n'existe pas, c'était dans le but de gérer cette exception que j'ai fait ce test. Mais il est vrai que c'est une exception qui est assez peu probable et donc qui ne mérite certainement pas que l'on y passe trop de temps.

Merci pour le temps passé pour cette issue et meilleures salutations.

Nolan Evard , étudiant
CPNV filière informatique, Sainte-Croix
SI-MI2b
***@***.***

On May 26, 2021 23:51, NicolasGlassey ***@***.***> wrote:

Bonsoir Nolan,

Je vous propose de tester si le fichier existe avant d'essayer de l'ouvrir. Evitant ainsi de réaliser un fopen sur un fichier inexistant.

Le résultat sur l'IHM est celui-là :

[image]<https://user-images.githubusercontent.com/5616312/119735668-f9bbf900-be7c-11eb-9f81-78d08d6a283a.png>

Et voilà le commit:
5e7b34a<https://github.com/NicolasGlassey/PROJWEB-INFOWEB/commit/5e7b34a236978d79d60b13bf82eaaa6d530aa464>

On regarde demain ensemble si besoin.

Bonne soirée !
